services:
  db:
    image: postgres:16
    container_name: msframework_db
    environment:
      POSTGRES_DB: msframework
      POSTGRES_USER: msframework
      POSTGRES_PASSWORD: msframework
    ports:
      - "5432:5432"
    volumes:
      - msframework_pgdata:/var/lib/postgresql/data

volumes:
  msframework_pgdata: